hacinternational/urls.py
from collections import OrderedDict

from django.conf.urls import url
from django.contrib import admin, sitemaps
from django.contrib.sitemaps.views import sitemap
from django.urls import path, reverse

from hacinternational.apps.about.views import WhoWeAreView, MeetTheTeamView
from hacinternational.apps.contact_us.views import (
    ContactUsView, ContactUsSuccessView)
from hacinternational.apps.donate.views import DonateView
from hacinternational.apps.events.views import EventView, EventsView
from hacinternational.apps.home.views import HomeView
from hacinternational.apps.volunteer.views import (
    VolunteerListView, VolunteerOpportunityView)



# class StaticViewSitemap(sitemaps.Sitemap):
#     priority = 0.5
#     changefreq = 'weekly'
#
#     def items(self):
#         return ['home']
#
#     def location(self, item):
#         return reverse(item)
#
#
# sitemaps = OrderedDict([
#     ('static', StaticViewSitemap),
# ])

admin.site.site_header = 'Hope For African Communities administration'

urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
    #     name='django.contrib.sitemaps.views.sitemap'),

    path('', HomeView.as_view(), name='home'),
    path('who-we-are/', WhoWeAreView.as_view(), name='who_we_are'),
    path('meet-the-team/', MeetTheTeamView.as_view(), name='meet_the_team'),
    path('donate/', DonateView.as_view(), name='donate'),
    path('contact-us/', ContactUsView.as_view(), name='contact_us'),
    path('contact-us/success', ContactUsSuccessView.as_view(),
         name='contact_us_success'),
    path('events/', EventsView.as_view(), name='events'),
    path('events/<int:event_id>/', EventView.as_view(), name='event'),
    path('volunteer/', VolunteerListView.as_view(), name='volunteer_list'),
    path('volunteer/<int:id>/', VolunteerOpportunityView.as_view(),
         name='volunteer_opportunity'),
]

hacinternational/apps/contact_us/models.py
from django.db import models

# Create your models here.

hacinternational/apps/donate/models.py
from django.db import models

# Create your models here.

hacinternational/apps/events/models.py
import datetime

from django.db import models
from ckeditor.fields import RichTextField

from hacinternational.apps.base_model import BaseModel


class EventActiveManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(
                models.Q(is_active=True) &
                models.Q(
                    models.Q(date__gte=datetime.datetime.now().date()) |
                    models.Q(date__isnull=True)
                )
        )


class Event(BaseModel):
    class Meta:
        ordering = ('date', 'created_at',)

    objects = models.Manager()
    active_objects = EventActiveManager()

    is_active = models.BooleanField(
        default=True,
        help_text='If not active, it will not be shown on the list of '
                  'current events')
    title = models.CharField(
        max_length=255, help_text='Title of the event')
    image = models.ImageField()
    date = models.DateField(
        help_text='Date of the event (if empty, will show TBA)',
        null=True, blank=False)
    location = models.CharField(
        max_length=255,
        help_text='Where the event will take place')
    description = RichTextField(
        help_text='Description of the event')

hacinternational/apps/volunteer/models.py
from django.db import models
from ckeditor.fields import RichTextField

from hacinternational.apps.base_model import BaseModel


DURATION_CHOICES = (
    ('short_term', 'Short Term'),
    ('long_term', 'Long Term')
)


class VolunteerOpportunityActiveManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)


class VolunteerOpportunity(BaseModel):
    class Meta:
        ordering = ('-created_at',)
        verbose_name = 'Volunteering opportunity'
        verbose_name_plural = 'Volunteering opportunities'

    objects = models.Manager()
    active_objects = VolunteerOpportunityActiveManager()

    is_active = models.BooleanField(
        default=True,
        help_text='If not active, it will not be shown on the list of '
                  'available opportunities')
    title = models.CharField(
        max_length=255,
        help_text='Main title for the volunteering opportunity')
    location = models.CharField(
        max_length=255,
        help_text='Where the volunteering opportunity will take place')
    duration = models.CharField(
        max_length=20, choices=DURATION_CHOICES, default=DURATION_CHOICES[0][0],
        help_text='How long the volunteering opportunity will take')
    description = RichTextField(
        help_text='What the volunteer will need to do (What will you be doing?)'
    )
    volunteer_profile = RichTextField(
        help_text='What kind of volunteer we are looking for '
                  '(Who are we looking for?)')
    reason = RichTextField(
        help_text='Why this is important (Why will you want to do this?)',
        null=True, blank=False)
    rewards = RichTextField(
        help_text='What the volunteer will get for doing this '
                  '(What will you get from this opportunity?)',
        null=True, blank=False)

    def __str__(self):
        return self.title

hacinternational/apps/contact_us/forms.py
from django import forms


class ContactUsForm(forms.Form):
    subject = forms.CharField(max_length=500)
    email_address = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

hacinternational/apps/events/forms.py
import datetime

from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from ckeditor.widgets import CKEditorWidget

from hacinternational.apps.events.models import Event


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = '__all__'

    date = forms.DateField(
        widget=AdminDateWidget(),
        help_text='Date of the event (if empty, will show TBA)', required=False)
    description = forms.CharField(
        widget=CKEditorWidget(), help_text='Description of the event')

    def clean_date(self):
        date = self.cleaned_data['date']
        if date < datetime.date.today():
            raise forms.ValidationError("The date cannot be in the past!")

        return date

hacinternational/apps/volunteer/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget

from hacinternational.apps.volunteer.models import VolunteerOpportunity


class VolunteerOpportunityForm(forms.ModelForm):
    class Meta:
        model = VolunteerOpportunity
        fields = '__all__'

    description = forms.CharField(
        widget=CKEditorWidget(),
        help_text='What the volunteer will need to do (What will you be doing?)'
    )
    volunteer_profile = forms.CharField(
        widget=CKEditorWidget(),
        help_text='What kind of volunteer we are looking for '
                  '(Who are we looking for?)')
    reason = forms.CharField(
        widget=CKEditorWidget(), required=False,
        help_text='Why this is important (Why will you want to do this?)')
    rewards = forms.CharField(
        widget=CKEditorWidget(), required=False,
        help_text='What the volunteer will get for doing this '
                  '(What will you get from this opportunity?)')

hacinternational/apps/about/views.py
from django.views.generic import TemplateView


class WhoWeAreView(TemplateView):
    template_name = 'pages/who_we_are.html'


class MeetTheTeamView(TemplateView):
    template_name = 'pages/meet_the_team.html'

hacinternational/apps/contact_us/views.py
from django.conf import settings
from django.urls import reverse_lazy
from django.core.mail import EmailMessage
from django.views.generic import FormView, TemplateView

from . import forms


class ContactUsView(FormView):
    template_name = 'pages/contact_us/form.html'
    form_class = forms.ContactUsForm
    success_url = reverse_lazy('contact_us_success')

    def get_initial(self):
        initial = super(ContactUsView, self).get_initial()

        if self.request.GET.get('subject'):
            initial['subject'] = self.request.GET['subject']

        return initial

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        email = EmailMessage(
            from_email=form.cleaned_data['email_address'],
            to=(settings.CONTACT_EMAIL,),
            subject=form.cleaned_data['subject'],
            body=form.cleaned_data['message'])

        email.send(fail_silently=False)
        return super(ContactUsView, self).form_valid(form)


class ContactUsSuccessView(TemplateView):
    template_name = 'pages/contact_us/form_success.html'

hacinternational/apps/donate/views.py
from django.views.generic import TemplateView


class DonateView(TemplateView):
    template_name = 'pages/donate.html'

hacinternational/apps/events/views.py
from django.http import Http404
from django.shortcuts import render
from django.views.generic import TemplateView

from hacinternational.apps.events.models import Event


class EventsView(TemplateView):
    template_name = 'pages/events.html'

    def get(self, request, *args, **kwargs):
        events = Event.active_objects.all()

        ctx = {
            'events': events
        }

        return render(request, self.template_name, ctx)


class EventView(TemplateView):
    template_name = 'pages/event.html'

    def get(self, request, event_id, *args, **kwargs):
        try:
            event = Event.active_objects.get(id=event_id)
        except Event.DoesNotExist:
            raise Http404('No VolunteerOpportunity matches the given query.')

        ctx = {
            'event': event
        }

        return render(request, self.template_name, ctx)

hacinternational/apps/home/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'pages/home.html'

hacinternational/apps/volunteer/views.py
from django.http import Http404
from django.shortcuts import render
from django.views.generic import TemplateView

from hacinternational.apps.volunteer.models import VolunteerOpportunity


class VolunteerListView(TemplateView):
    template_name = 'pages/volunteer/list.html'

    def get(self, request, *args, **kwargs):
        opportunities = VolunteerOpportunity.active_objects.all()

        ctx = {
            'opportunities': opportunities
        }

        return render(request, self.template_name, ctx)


class VolunteerOpportunityView(TemplateView):
    template_name = 'pages/volunteer/opportunity.html'

    def get(self, request, id, *args, **kwargs):
        try:
            opportunity = VolunteerOpportunity.active_objects.get(id=id)
        except VolunteerOpportunity.DoesNotExist:
            raise Http404('No VolunteerOpportunity matches the given query.')

        ctx = {
            'opportunity': opportunity
        }

        return render(request, self.template_name, ctx)

hacinternational/templates/pages/volunteer/list.html
{% extends 'base.html' %}
{% load static %}
{% load pipeline %}

{% block content %}
<section class="container-fluid bg-light mb-5">
  <div id="main" class="container pb-3 pt-3">
    {% include 'partials/page_title.html' with page_title='Volunteer' %}

    <section class="row">
      <div class="col-12">
        <p class="lead">Hope For African Communities is a new charity and we need help to provide a better life for those in need. You can find all our current volunteering opportunities in the list below.</p>
        <p>If you want to help us but you can't find the right opportunity for you in this list, feel free to <a href="{% url 'contact_us' %}?subject=Spontaneous Volunteering">contact us</a> as we would love to hear from you.</p>
      </div>
    </section>
  </div>
</section>

<section class="container">
  {% if opportunities %}
    {% for opportunity in opportunities %}
      <div class="row justify-content-center">
        <div class="col-12">
          <h2 class="sub-heading">{{ opportunity.title }}</h2>
          <p class="font-weight-bold">{{ opportunity.get_duration_display }}</p>
          <p><span class="font-weight-bold">Location: </span>{{ opportunity.location }}</p>
          <div class="truncate-text-multiline">
              {{ opportunity.description | safe }}
          </div>
          <div class="mt-2">
            <a href="{% url 'contact_us' %}?subject=Volunteer for: {{ opportunity.title }}" class="btn btn-primary mr-2">Apply</a>
            <a href="{% url 'volunteer_opportunity' id=opportunity.id %}" class="btn btn-secondary">Read more</a>
          </div>
        </div>
      </div>
      {% if not forloop.last %}
        <hr class="display-4 my-4">
      {% endif %}
    {% endfor%}
  {% else %}
    <div class="text-center">
      <p class="lead">We are sorry, but at the moment we do not have any volunteering opportunities available.</p>
      <p>Feel free to <a href="{% url 'contact_us' %}?subject=Spontaneous Volunteering">contact us</a> as we are always in need of good help.</p>
    </div>
  {% endif %}
</section>
{% endblock %}

hacinternational/templates/pages/volunteer/opportunity.html
{% extends 'base.html' %}
{% load static %}
{% load pipeline %}

{% block content %}
<section class="container-fluid bg-light mb-5">
  <div id="main" class="container pb-3 pt-3">
    {% include 'partials/page_title.html' with page_title='Volunteer for <span class="sub-heading">'|add:opportunity.title|add:'</span>' %}
    <p><span class="font-weight-bold">Duration: </span>{{ opportunity.get_duration_display }}</p>
    <p><span class="font-weight-bold">Location: </span>{{ opportunity.location }}</p>
  </div>
</section>

<section class="container">
  <div class="row justify-content-center">
    <div class="col-12">
      <h2 class="sub-heading">What will you be doing?</h2>
      <p>{{ opportunity.description | safe }}</p>

      <h2 class="sub-heading mt-4">Who are we looking for?</h2>
      <p>{{ opportunity.volunteer_profile | safe }}</p>

      {% if opportunity.reason %}
        <h2 class="sub-heading mt-4">Why will you want to do this?</h2>
        <p>{{ opportunity.reason | safe }}</p>
      {% endif %}

      {% if opportunity.rewards %}
        <h2 class="sub-heading mt-4">What will you get from this opportunity?</h2>
        <p>{{ opportunity.rewards | safe }}</p>
      {% endif %}

      <div class="mt-5">
        <a href="{% url 'contact_us' %}?subject=Volunteer for: {{ opportunity.title }}" class="btn btn-primary mr-2">Volunteer Now</a>
        <a href="{% url 'volunteer_list' %}" class="btn btn-secondary">Go Back</a>
      </div>
    </div>
  </div>
</section>
{% endblock %}